# Generated by Django 2.2 on 2022-02-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20220226_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='text',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='title',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='img',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='job',
            field=models.CharField(default=23, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='name',
            field=models.CharField(default=23, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='phone',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
    ]
